name: CI
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.94.0
        id: stable
        with:
          components: clippy
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-target-${{ steps.stable.outputs.cachekey }}-${{ hashFiles('Cargo.lock') }}
      - run: cargo build --tests
      - run: cargo test
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo +nightly fmt --all --check
      - run: cargo doc --no-deps
        env:
          RUSTDOCFLAGS: -D warnings
